image: node:10-alpine
pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install hexo-cli -g
  - npm install
  - hexo clean && hexo g
  artifacts:
    paths:
    - public
  only:
  - master