name: HEXO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configuration environment
        env:
          QQ_RSA: ${{secrets.qq_rsa}}
        run: |
          mkdir -p ~/.ssh/
          echo "$QQ_RSA" > ~/.ssh/qq_rsa
          chmod 600 ~/.ssh/qq_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'yanglei0827'
          git config --global user.email '1912739092@qq.com'
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
      - name: Deploy hexo
        run: |
          hexo clean && hexo g